export const ChargePointDataMock = [
  {
    stationName: 'Paddington 36',
    location: 'W2 5TY, UK',
    availableChargePoints: '9',
    totalChargePoints: '18',
    isFavourite: true,
    distance: '140',
  },
  {
    stationName: 'London 2',
    location: 'W2 5TY, UK',
    availableChargePoints: '3',
    totalChargePoints: '10',
    isFavourite: false,
    distance: '12000',
  },
  {
    stationName: 'London 4',
    location: 'W2 5TY, UK',
    availableChargePoints: '4',
    totalChargePoints: '10',
    isFavourite: false,
    distance: '12000',
  },
  {
    stationName: 'London 5',
    location: 'W2 5TY, UK',
    availableChargePoints: '5',
    totalChargePoints: '10',
    isFavourite: false,
    distance: '12000',
  },
  {
    stationName: 'London 6',
    location: 'W2 5TY, UK',
    availableChargePoints: '8',
    totalChargePoints: '10',
    isFavourite: false,
    distance: '12000',
  },
  {
    stationName: 'London 8',
    location: 'W2 5TY, UK',
    availableChargePoints: '1',
    totalChargePoints: '10',
    isFavourite: false,
    distance: '12000',
  },
  {
    stationName: 'Loughborough towncentre hall2',
    location: 'LE11 EC3, UK',
    availableChargePoints: '5',
    totalChargePoints: '5',
    isFavourite: true,
    distance: '780',
  },
];
